#! /bin/sh
BASEDIR=`dirname $0`
PROJECTDIR=$(cd ${BASEDIR}/../../; pwd)
PROJECTNAME=`basename ${PROJECTDIR}`
CONTAINERNAME=devbox-${PROJECTNAME}

docker kill ${CONTAINERNAME}
docker rm ${CONTAINERNAME}

