#! /bin/sh
BASEDIR=`dirname $0`
PROJECTDIR=$(cd ${BASEDIR}/../../; pwd)
PROJECTNAME=`basename ${PROJECTDIR}`

if [ $# -lt 1 ]; then
  GAS_CONFIG_DIR=$(cd ${PROJECTDIR}/../.gas-manager; pwd)
else
  GAS_CONFIG_DIR=$1
fi

docker run -it -d \
  --name="devbox-${PROJECTNAME}" \
  -v ${PROJECTDIR}:/home/project \
  -v ${GAS_CONFIG_DIR}:/home/.gas-manager \
  -w /home/project \
  tyskdm/devbox-gas:latest bash

